apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-pdf
spec:
  replicas: 4
  selector:
    matchLabels:
      app: download-pdf
  template:
    metadata:
      labels:
        app: download-pdf
    spec:
      containers:
        - name: download-pdf
          image: download-pdf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

